name: Tests
on: [push, pull_request]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - name: Lint
      run: npm run -s pretest
    - name: Tests
      run: npm run -s tests-only
    - name: Coverage
      run: npm run -s posttest
